spring:
  redis:
    host: "redis"
    port: 6379
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
  application:
    name: consumer
  profiles:
    active: dev
eureka:
  client:
    register-with-eureka: true  
    fetch-registry: true
    service-url:
      defaultZone: http://3.38.23.41:8761/eureka

server:
  port: 5020
cloud:
  aws:
    credentials:
      accessKey: AKIA2SJCWGIOHZXVYN5I
      secretKey: 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
    s3:
      bucket: youngcha-coin-service
      key: coinlist/coin-list.json
    region:
      static: ap-northeast-2
    stack:
      auto: false
property:
  desturi: https://api.bithumb.com/public/ticker/ALL_KRW
  candlestickuri: https://api.bithumb.com/public/candlestick/
  kafka:
    server: 3.36.162.130:9092
    group: consumer-group
